### PR TITLE
Adding cartoon by Tjeerd Royaards

### PR DESCRIPTION
**Pull request by cow-n-berg**

### CODE REVIEW

**Comment by cow-n-berg** [comment]
Cover was put together by myself from Twitter avatar and cartoon autograph. 

Example was only slightly larger (700 pixels wide). Original version: https://tjeerdroyaards.typepad.com/.a/6a017d3d8326e2970c0223c84ebf73200c-700wi as published on https://tjeerdroyaards.typepad.com/my-blog/2018/05/index.html

**Comment by cow-n-berg** [comment]
info.json should start with
  "name": "Tjeerd Royaards: Political Cartoons",
to sort it with the T's

**Comment by tardypad** [comment]
Sorry but I think I'll revert the merging of this PR before making a new release.
Political cartoons do not really fit within the app.
See https://openrepos.net/comment/9910#comment-9910

**Comment by Maledictus** [comment]
Damien, let's I revert PR with this comics

ср, 2 янв. 2019 г. в 13:42, Damien Tardy-Panis <notifications@github.com>:

**Pull request merged**
