### PR TITLE
Add erzaehlmirnix (again)

### PR DESCRIPTION
**Pull request by Olf0**
Add erzaehlmirnix, now from Facebook.

Original PNGs:
- [cover.v3.png](https://user-images.githubusercontent.com/16547876/76672053-76292b80-659a-11ea-9749-1f9b66b358ac.png) and upscaled from it [cover_big.v3.png](https://user-images.githubusercontent.com/16547876/76672518-a625fe00-659d-11ea-8514-f3345f5c1554.png)  
  The basis for the cover was [ERKZsSZXkAIqe09_v3.png](https://user-images.githubusercontent.com/16547876/76476245-aee1cd00-6401-11ea-9438-f9200cbad84b.png), cut from [ERKZsSZXkAIqe09.png](https://user-images.githubusercontent.com/16547876/76362708-cb0e3d00-6321-11ea-81d0-8df1cf681e80.png)
- [example3.png](https://user-images.githubusercontent.com/16547876/76362801-014bbc80-6322-11ea-9319-092daee57e82.png)

### CODE REVIEW

**Comment by Olf0** [comment]
The background of the original [cover_big_v3a_1000.png](https://user-images.githubusercontent.com/16547876/76362278-09572c80-6321-11ea-8953-644a2c417d5b.png) PNG (1000x1000 px²; mind the first few lines, which are accidentally black) still has to be flood-filled with the RGB background colour `dddfde` from the [info.json](https://github.com/tardypad/sailfishos-daily-comics/blob/38520a79245eab962b1c2fe6ac80f69c006aba24/plugins/erzaehlmirnix/info.json) file, saved and then downscaled to 300x300 px².  
Both PNGs then have to be exported as JPEGs again and uploaded to replace the extant [cover_big.jpg](https://github.com/tardypad/sailfishos-daily-comics/blob/38520a79245eab962b1c2fe6ac80f69c006aba24/plugins/erzaehlmirnix/cover_big.jpg) and [cover.jpg](https://github.com/tardypad/sailfishos-daily-comics/blob/38520a79245eab962b1c2fe6ac80f69c006aba24/plugins/erzaehlmirnix/cover.jpg).

As I currently lack access to an image manipulation software with which this can be accomplished easily, this may take a while.

**Comment by Olf0** [comment]
The background of the original [cover.v3.png](https://user-images.githubusercontent.com/16547876/76672053-76292b80-659a-11ea-9749-1f9b66b358ac.png) PNG still has to be flood-filled with the RGB background colour `dddfde` from the [info.json](https://github.com/tardypad/sailfishos-daily-comics/blob/38520a79245eab962b1c2fe6ac80f69c006aba24/plugins/erzaehlmirnix/info.json) file, saved and then upscaled to 1000x1000 px².  
Both PNGs then have to be exported as JPEGs again and uploaded to replace the extant [cover_big.v3.jpg](https://user-images.githubusercontent.com/16547876/76672566-ef764d80-659d-11ea-8e6e-eff7ce6580e3.jpg) and [cover.v3.jpg](https://user-images.githubusercontent.com/16547876/76672023-38c49e00-659a-11ea-9dd4-a3c39d3414aa.jpg).

As I currently lack access to an image manipulation software with which this can be accomplished easily, this may take a while.

**Comment by Olf0** [comment]
* Created [cover.v4-freed.png](https://user-images.githubusercontent.com/16547876/76672368-788c8500-659c-11ea-82c6-14887579bab8.png)
* Copied it upon background colour `dddfde`, resulting in [cover.v4.png](https://user-images.githubusercontent.com/16547876/76693989-50b92200-666d-11ea-9b8e-24f0693d0c2b.png)
* Upscaled it to [cover_big.v4.png](https://user-images.githubusercontent.com/16547876/76707864-037f9380-66f3-11ea-901f-e644c876c1a9.png) and exported both as [cover.v4.jpg](https://user-images.githubusercontent.com/16547876/76707889-2dd15100-66f3-11ea-8bf2-a2b61d3b2e74.jpg) and [cover_big.v4.jpg](https://user-images.githubusercontent.com/16547876/76707924-52c5c400-66f3-11ea-898a-b6cbbcf76c66.jpg)

**Comment by Maledictus** [comment]
It's the same comics as emoticomix but in de language. I'm not sure that we should add the same comics in different languages as two different comics. I'm going to merge only en version but we can create issue about adding multilanguage support to application
P.S.
We already have #17 and #54 . If I have time I will do it in the next release

**Comment by Olf0** [comment]
> It's the same comics as emoticomix but in de language.

Rather the opposite: erzaehlmirnix is the original version, its author started to translate most of the new strips and publish them as emoticomix recently.  Note, that emoticomix is not a third party translation, it is the author who releases most of her strips also in English.
  
> I'm not sure that we should add the same comics in different languages as two different comics.

As soon as an alternative mechanism for multi-language comics is implemented (solving issues #17 and #54), I will gladly convert erzaehlmirnix and emoticomix to a shared base and provide two language options (DE and EN) for it.

Note that the erzaehlmirnix's requirements for this mechanism are:
* Primary / original language can be arbitrarily set (here: to DE)
* The names of the different language versions differ (also true for some other comic strips, for which translations are available)
* Hence different cover images must be used (as they may include names or words, which vary between languages)

If you plan to make a release of DailyComics, before a multi-language mechanism fulfilling these requirements is implemented, please include both, erzaehlmirnix and emoticomix.
If you insist in including only one of them for now, please include the original (erzaehlmirnix) instead of its (sometimes strangely translated) English version (emoticomix).

I will retain both branches, until we have found a working solution for both, erzaehlmirnix and emoticomix.

**Comment by Olf0** [comment]
Stopped working, and I failed to make it working again, neither from Facebook or from Twitter.

**Pull request closed without merging**
