### PR TITLE
Move problem menu to pushup menu and add copy url to clipboard menu item

### PR DESCRIPTION
**Pull request by Maledictus**
I have added to pulldown menu "Copy url to clipboard" item and move item with "problem" to pushup menu.

### CODE REVIEW

**Comment by tardypad** [comment]
Thanks for this!

I will only take the first part of the commit though (adding to clipboard in pullDown menu)
The report problem item was already previously in a pushUp menu like you've put it. But people told me that it was annoying there as it happened too often to be triggered inadvertently.
See commit c2d5535 about this.

The pullDown menu will get a bit too crowded now with 4 items. But that should still be acceptable.
If I ever get time for it, it would be cool to have a proper share functionality #7.
But for now the clipboard will do part of the job!

**Comment by tardypad** [comment]
I've merged your changes in ddab3e0
But since the commit is amended as described before, Github can't automatically mark this PR as merged.

**Comment by Maledictus** [comment]
Np. Ur app is very good!
I can add full share functionality (I have experience in it) and try to implement zooming, but you will be prohibited from harbour.

**Comment by tardypad** [comment]
Harbour prohibition is not a problem
The app is already not allowed in there for "copyright" reasons
https://openrepos.net/comment/6963#comment-6963

**Comment by Maledictus** [comment]
Ok. I will try to make some PR during weekend

**Pull request closed without merging**
