### PR TITLE
Fix "Suporte", i.e., Vida de Suporte

### PR DESCRIPTION
**Pull request by Olf0**
Richer RegEx: ]* src="(https://vidadesuporte.com.br/wp-content/uploads/20[2-9][0-9]/[01][0-9]/Suporte_[0-9]+\.[-+_0-9A-Za-z]+)"

### CODE REVIEW

**Comment by Olf0** [comment]
**ToDo**: Rename `plugins/suporte` to `plugins/vidadesuporte` to avoid *extant* (i.e., already existing) ambiguity.

**Review by Olf0 — COMMENTED** [review]
LGTM

**Comment by Maledictus** [comment]
Hi, Sorry, but I don't have time to work on this application now. But if you'd like to fix regeхp for comics, please, use `plugins/update.json` file. In this case all applications will reread on start this file and update all comics without reinstalling new version

**Comment by Olf0** [comment]
> Hi, Sorry, but I don't have time to work on this application now.

I know, see issue #137.

> But if you'd like to fix regeхp for comics, please, use `plugins/update.json` file. In this case all applications will reread on start this file and update all comics without reinstalling new version.

Because this is basically a new comic by renaming an extant one (to its real, unambiguous name), this means I should delete its entry in `plugins/update.json`, correct?

Will do so, if you confirm.

**Comment by Olf0** [comment]
Merged as https://github.com/sailfishos-applications/daily-comics/pull/12

**Pull request closed without merging**
