### PR TITLE
French Translation

### PR DESCRIPTION
**Pull request by lutinotmalin**
Hi mate,

I love your Daily Comics app, use it everyday. I decided to translate it to my main language, which is French.

Is it possible to add that translation to your app ? Don't hesitate to look at the code and the lines, as I don't really know how it would look like whithin the app. It should be OK but we never know. 

French is a little more complicated than English, we need more words to express ourselves...

Cheers ! :+1:

### CODE REVIEW

**Comment by lutinotmalin** [comment]
I polished a little bit the file. The third commit should be the last one.

**Comment by lutinotmalin** [comment]
I guess this is the last time I'm editing the file. It should be OK :+1:

**Comment by lutinotmalin** [comment]
I guess this is the last time I'm editing the file. It should be OK now.

**Comment by lutinotmalin** [comment]
I guess this is the last time I'm editing the file... It should be OK now, according to the app rendering.

**Comment by lutinotmalin** [comment]
Up ! Any news about Daily Comics future update ? :)

The last translation (e1d263a) is the good one. Should not change now.

**Comment by tardypad** [comment]
@lutinotmalin yeah I'm gonna make an update soon one of these days
will add a few comics and merge the current PRs at least

Sorry I didn't reply before, I usually wait to have "enough" tasks planned on it before starting working on the next release

**Comment by lutinotmalin** [comment]
Great ! Can't wait to get that update ! :+1:

**Comment by tardypad** [comment]
Thanks for the translation!
I've squashed the commits into one and merged it
https://github.com/tardypad/sailfishos-daily-comics/commit/cb118d808e1bc3c4c7c53d1f216de24ee225c980

**Pull request closed without merging**
